name: Create JSON

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create JSON
        run: |
          echo '{ "name": "example", "version": "1.0.0" }' > data.json

      - name: Use JSON
        run: |
          cat data.json
