name: Multiple Action

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "secrets.json"
        json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    - name: Access Secrets
      run: |
        echo "Secret Token : ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"
